name: Build Docker Image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Fitbit-Manager Custom Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification of build start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "#4381de"
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Start Fitbit-Manager image build
          SLACK_MESSAGE: |
            Run number : #${{ github.run_number }}

      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Get Tag from Release
        run: echo "ImageTag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        if: github.event_name == 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/walnuts1018/fitbit-manager:latest
            ghcr.io/walnuts1018/fitbit-manager:${{ env.ImageTag }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        if: github.event_name != 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/walnuts1018/fitbit-manager:test-latest
            ghcr.io/walnuts1018/fitbit-manager:test-${{ github.sha }}-${{ github.run_number }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "ghcr.io/walnuts1018/fitbit-manager:test-${{ github.sha }}-${{ github.run_number }}"
          format: "sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  SucceessNotification:
    if: ${{ success() }}
    name: Send Success Message
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Fitbit-Manager image build succeeded
          SLACK_MESSAGE: |
            Image: Fitbit Manager
            Run number : #${{ github.run_number }}

  FailureAlert:
    if: ${{ failure() }}
    name: Notify failure
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Alert to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Fitbit-Manager image build failed
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            Image: Fitbit Manager
            Run number : #${{ github.run_number }}
