name: Build Docker Image
on:
  release:
    types: [published]

jobs:
  build:
    name: Build Fitbit-Manager Custom Docker Image
    runs-on: ubuntu-latest
    outputs:
      ImageTag: ${{ steps.GetTag.outputs.ImageTag }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.8.0
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Get Tag from Release
        id: GetTag
        run: |
          echo "ImageTag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/walnuts1018/fitbit-manager:latest
            ghcr.io/walnuts1018/fitbit-manager:${{ steps.GetTag.outputs.ImageTag }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "ghcr.io/walnuts1018/fitbit-manager:${{ needs.build.outputs.ImageTag }}"
          format: "sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
