name: Go Tests
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: go mod download
        run: go mod download

      - name: Test
        run: |
          go test  -cover ./... -coverprofile="cover.out"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.out
          fail_ci_if_error: false
          verbose: true

  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
